### ISSUE TITLE
Minimum claim fee isn't being collected

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/core-contracts#100]
**Describe the bug**
With the implementation of https://github.com/Geo-Web-Project/core-contracts/pull/98, we now require a Minimum For Sale Price for parcels across actions. When claiming a new parcel after the end of the Fair Launch Auction, this Minimum For Sale Price should also be the minimum fee paid by the user to make the claim (regardless of the user's submitted price). This fee is not being collected currently. 

Note: the contracts are properly enforcing the Min For Sale Price.

**Comment by codynhat** [comment]
> @codynhat I was also able to lower a parcel's `For Sale Price` below the minimum (Parcel 0x12 on https://goerli.etherscan.io/tx/0xe2bb7503cf903295d6e71609c0adde61b22b777cd35f17d5d6f0a19444b81ab8), so can you double check that logic too when you work on this ticket?

As mentioned offline, the minimum for sale price has not been deployed yet.
