### ISSUE TITLE
Create a new AuctionETHClaimer smart contract for "Fair Launch"

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/core-contracts#26]
**Overview**
To make the Geo Web core contracts more extensible, we are porting existing smart contract logic to new more modular ones. These new contracts use a role based permissions model.

This ticket is for new fair launch auction logic under this new archtecture.

**Business Requirements**
https://github.com/Geo-Web-Project/garden/blob/main/content/notes/Fair%20Launch%20Auction%20Requirements.md

**Technical Spec**
https://github.com/Geo-Web-Project/garden/blob/main/content/notes/Draft%20Proposal%20-%20FairLaunchClaimer.md

**Bounty**
Size = Medium
Reason = New auction logic; follow new contract architecture
Payment = .25 ETH
Assignee = brossetti1

**Bounty Submission**
When work is complete, please create PR with your work and request review from both @codynhat & @gravenp. @gravenp will handle logistics of payment with you privately.

**Comment by brossetti1** [comment]
@gravenp so we merged the Fair Launch Auction contract, just fyi

**Comment by brossetti1** [comment]
merged, closing ticket @gravenp

**Comment by gravenp** [comment]
Bounty paid here: https://etherscan.io/tx/0x8b661fe692282cd6c731ccfc7ca018d359e8c46296ab7c8f2985fa8cddbf9b22
