### ISSUE TITLE
create Reclaimer contract

### ISSUE THREAD

**Issue by brossetti1** [Geo-Web-Project/core-contracts#51]
**Overview**
To make the Geo Web core contracts more extensible, we are porting existing smart contract logic to new more modular ones. These new contracts use a role based permissions model.

This ticket is for new reclaimer auction logic under this new archtecture for the super app.

**Business Requirements**
TODO

**Technical Spec**
TODO

**Comment by brossetti1** [comment]
@gravenp can you make a set of technical specs for this one and I can link them in the issue?

**Comment by gravenp** [comment]
Business Requirements - https://github.com/Geo-Web-Project/garden/blob/main/content/notes/Reclaimer%20Requirements.md

Draft Technical Specs (developer feedback needed) - https://github.com/Geo-Web-Project/garden/blob/main/content/notes/Draft%20Proposal%20-%20Reclaimer.md

**Comment by gravenp** [comment]
Completed
