### ISSUE TITLE
Bid collateral of new purchase price

### ISSUE THREAD

**Issue by codynhat** [Geo-Web-Project/core-contracts#53]
Per discussion [here](https://forum.geoweb.network/t/owner-forgiving-auctions-specification-discussion/43/20?u=codynhat), the collateral needed for a bid should be the new purchase price. The collateral is redeemed upon acceptance or rejection of the bid.

**Comment by gravenp** [comment]
Completed with https://github.com/Geo-Web-Project/core-contracts/pull/61
