### ISSUE TITLE
Accept incoming bids EQUAL TO or greater than the current For Sale Price

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/core-contracts#66]
**Describe the bug**
Contracts are rejecting incoming bids for parcels that have the bid value set equal to the current For Sale Price and should accept them.

**To Reproduce**
1. Go to a parcel you don't own on the Cadastre
2. Attempt to submit a bid with a value equal to the current For Sale Price (UI lets you)
3. Transaction is rejected

**Expected behavior**
The contracts like the UI should allow bids values equal to or greater than the current For Sale Price (even though the scenario isn't likely).s

**Comment by lolboysg** [comment]
PR has been merged so issue can be closes @gravenp
